INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (3, 'Afrikaans', 'af');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (4, 'Albanian', 'al');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (5, 'Arabic', 'ar');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (6, 'Azerbaijani', 'az');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (7, 'Bulgarian', 'bg');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (8, 'Catalan', 'ca');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (9, 'Czech', 'cz');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (10, 'Danish', 'da');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (11, 'German', 'de');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (12, 'Greek', 'el');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (13, 'Basque', 'eu');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (14, 'Persian (Farsi)', 'fa');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (15, 'Finnish', 'fi');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (16, 'French', 'fr');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (17, 'Galician', 'gl');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (18, 'Hebrew', 'he');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (19, 'Hindi', 'hi');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (20, 'Croatian', 'hr');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (21, 'Hungarian', 'hu');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (22, 'Indonesian', 'id');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (23, 'Italian', 'it');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (24, 'Japanese', 'ja');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (25, 'Korean', 'kr');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (26, 'Latvian', 'la');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (27, 'Lithuanian', 'lt');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (28, 'Macedonian', 'mk');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (29, 'Norwegian', 'no');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (30, 'Dutch', 'nl');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (31, 'Polish', 'pl');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (32, 'Portuguese', 'pt');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (33, 'Português Brasil', 'pt_br');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (34, 'Romanian', 'ro');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (35, 'Russian', 'ru');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (36, ' Swedish', 'sv');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (37, 'Slovak', 'sk');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (38, 'Slovenian', 'sl');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (39, 'Spanish', 'sp');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (40, 'Serbian', 'sr');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (41, 'Thai', 'th');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (42, 'Turkish', 'tr');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (43, 'Ukrainian', 'uk');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (44, 'Vietnamese', 'vi');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (45, 'Chinese Simplified', 'zh_cn');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (46, 'Chinese Traditional', 'zh_tw');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (47, 'Zulu', 'zu');
INSERT INTO public."Languages" (lang_id, name, lang_key) VALUES (1, 'English', 'en');